// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMkUjdlCk6c_temktHASp59UK2xE74kBQ',
    appId: '1:205317054087:web:5f631c89e71902e4052222',
    messagingSenderId: '205317054087',
    projectId: 'test-598f2',
    authDomain: 'test-598f2.firebaseapp.com',
    storageBucket: 'test-598f2.appspot.com',
    measurementId: 'G-NQ6RJ3KWP8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiHFwGlWYJSk8veTW3OSgQfVe9bsocKJg',
    appId: '1:205317054087:android:8893dbef857f739c052222',
    messagingSenderId: '205317054087',
    projectId: 'test-598f2',
    storageBucket: 'test-598f2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrR1mYIgbaXfKPR2ExsouQH3rLbGeOVm4',
    appId: '1:205317054087:ios:af27440735ff378d052222',
    messagingSenderId: '205317054087',
    projectId: 'test-598f2',
    storageBucket: 'test-598f2.appspot.com',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrR1mYIgbaXfKPR2ExsouQH3rLbGeOVm4',
    appId: '1:205317054087:ios:741d6898d37a0c73052222',
    messagingSenderId: '205317054087',
    projectId: 'test-598f2',
    storageBucket: 'test-598f2.appspot.com',
    iosBundleId: 'com.example.firebaseTest.RunnerTests',
  );
}
